import Head from "next/head";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import { UploadImage } from "~/components/upload-pdf";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const [files, setFiles] = useState<File[]>([]);

  async function sendPdf(file: File) {
    const formData = new FormData();
    formData.append("file", file);
  
    const res = await fetch("/api/upload", {
      method: "POST",
      body: formData,
    });
    console.log(res);
    return res.json();
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">HACKNATION</span>
          </h1>
          <div className="flex w-full justify-center">
            <UploadImage
              title={"Upload PDF"}
              files={files}
              setFiles={setFiles}
              maxFileNumber={1}
            />
          </div>
          <Button disabled={!files.length} variant="outline" onClick={() => sendPdf(files[0] as File)}>Create submission</Button>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
