import Head from "next/head";
import { BadgeCheckIcon, ChevronRightIcon } from "lucide-react";
import { useState } from "react";
import { Button } from "~/components/ui/button";
import {
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemMedia,
  ItemTitle,
} from "~/components/ui/item";
import { UploadImage } from "~/components/upload-pdf";

import { api } from "~/utils/api";
import Link from "next/link";

export default function Home() {
  const queryClient = api.useUtils();
  const { data: submissions } = api.post.getAll.useQuery();
  const { mutate, isPending: isCreating } = api.post.create.useMutation({
    onSuccess: async () => {
      void (await queryClient.post.getAll.invalidate());
      setFiles([]);
    },
  });
  const [files, setFiles] = useState<File[]>([]);

  async function sendPdf(file: File) {
    const formData = new FormData();
    formData.append("file", file);

    const res = await fetch("/api/upload", {
      method: "POST",
      body: formData,
    });

    const data: unknown = await res.json();
    console.log(data);
    mutate({ name: file.name + Date.now().toString() });
    return data;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">HACKNATION</span>
          </h1>
          <div className="flex w-full justify-center">
            <UploadImage
              title={"Upload PDF"}
              files={files}
              setFiles={setFiles}
              maxFileNumber={1}
            />
          </div>
          <Button
            disabled={!files.length || isCreating}
            variant="outline"
            onClick={() => sendPdf(files[0]!)}
          >
            {isCreating ? "Creating submission..." : "Create submission"}
          </Button>
          <p className="text-2xl text-white">
            {submissions?.length
              ? submissions.map((submission) => (
                  <Item
                    variant="outline"
                    size="sm"
                    asChild
                    key={submission.id}
                    className="m-5"
                  >
                    <Link href={`/submission/${submission.id}`}>
                      <ItemMedia>
                        <BadgeCheckIcon className="size-5" />
                      </ItemMedia>
                      <ItemContent className="flex flex-row gap-2">
                        <ItemTitle>{submission.name}</ItemTitle>
                        <ItemDescription>
                          Status: {submission.status}
                        </ItemDescription>
                      </ItemContent>
                      <ItemActions>
                        <ChevronRightIcon className="size-4" />
                      </ItemActions>
                    </Link>
                  </Item>
                ))
              : "Nothing had been submitted yet."}
          </p>
        </div>
      </main>
    </>
  );
}
